server:
  port: 8083
spring:
  cloud:
    gateway:
      routes:
        - id: springboot-security
          uri: http://localhost:8081/
          Predicates:
            - Path=/api/**         
  application:
    name: gateway
